#!/bin/bash
opcion=-1

while [ "$opcion" -ne 0 ]; do
    echo ""
    echo "==================="
    echo "=      MENU       ="
    echo "==================="
    echo "1. Acciones en Directorios"
    echo "2. Acciones en Archivos"
    echo "3. Acciones sobre el contenido de un archivo"
    echo "4. Cambiar permisos de un archivo o directorio"
    echo "5. Mostrar fecha y hora"
    echo "6. Mostrar calendario"
    echo "7. Archivo de Log"
	echo "0. Salir"
	echo "==================="
    echo "Ingrese la opcion que desea seleccionar: "
	read opcion

    case $opcion in
    	1)
        	echo "--- SUBMENU: ACCIONES EN DIRECTORIOS ---"
        	echo "a) Crear directorio"
            echo "b) Eliminar directorio"
			echo "Seleccione una opcion: " 
            read OpcionDirect
		            
           	if [ "$OpcionDirect" = "a" ]; then
            	echo "Nombre del directorio a crear: " 
				read dir
            	if [ -d "$dir" ]; then
            		echo "ERROR: El directorio ya existe."
                	else
                    mkdir "$dir"
                    echo "Directorio creado con exito."
               	fi

            	elif [ "$OpcionDirect" = "b" ]; then
                	echo "Nombre del directorio a borrar: " 
					read dir
               		if [ -d "$dir" ]; then
              			rmdir "$dir" 2>/dev/null #dsp fijarse si eliminar tmb el archivo aunque tenga archivos dentro
               			echo "Directorio eliminado."
                	else
               			echo "ERROR: El directorio no existe."
                fi
            	else
            		echo "Opcion no valida."

            	fi
            	;;

        2)
    	   	echo "--- SUBMENU: ACCIONES EN ARCHIVOS ---"
        	echo "a) Eliminar archivo"
	    	echo "b) Copiar archivo"
        	echo "c) Mover archivo"	
	    	echo "d) Mostrar permisos"
	    	echo "e) Mostrar archivos de un directorio"    
			echo "Seleccione una opcion: " 
			read OpcionArch
			
			if [ "OpcionArch" = "a" ]; then
				echo "Ingrese el nombre del archivo a borrar: "
				read archivo	
				if [ -f "$archivo" ]; then
    				rm $archivo
					echo "El archivo fue eliminado con exito."
				else
					echo "ERROR: El archivo no existe."
				fi		
	 
			elif [ "$OpcionArch" = "b"  ]; then 
				echo "Ingrese el archivo: "
				read origen
				echo "Ingrese el nombre o ruta de destino para el archivo: "
				read "destino"				
				if [ -f "$origen" ]; then
					cp "$origen" "$destino"
					echo "El archivo fue copiado con exito."
				else
					echo "ERROR: El archivo original no existe."
			fi
			
			elif [ "$OpcionArch" = "c" ]; then
				echo "Ingrese el archivo que desea mover: "
				read origen 
				echo "Ingrese el nombre o ruta de destino para el archivo: "
				read destino 

				if [ -f "origen" ]; then
					mv "$origen" "$destino"
					echo "El archivo fue movido con exito."
				else
					echo "ERROR: El archivo original no existe.  
			fi

			elif
	
			;;
			
        	
		3)
			    echo "--- SUBMENU: AGENDA ---"
			
			    # Crear el archivo si no existe
			    touch archivo.txt
			
			    echo "a) Guardar sus datos en un archivo"
			    echo "b) Ver el contenido completo del archivo"
			    echo "c) Ver línea en particular"
			    echo "d) Buscar y mostrar información de una persona ingresando la CI y campo a mostrar"
			    echo "e) Eliminar una línea del archivo según la CI ingresada"
			    echo "f) Modificar el teléfono de una persona a través de su CI"
			
			    read -p "Ingrese la opción que desea ejecutar, en caso de no requerir ninguna inserte 0: " option
			
			    case $option in
			
			        a)
			            read -p "Ingrese su CI: " ci
			            read -p "Ingrese su nombre: " nombre
			            read -p "Ingrese su apellido: " apellido
			            read -p "Ingrese su teléfono: " telefono
			            read -p "Ingrese su fecha de nacimiento: " fechaNacimiento
			
			            echo "$ci;$nombre;$apellido;$telefono;$fechaNacimiento" >> archivo.txt
			
			            echo "Datos guardados correctamente."
			            ;;
			
			        b)
			            echo "--- CONTENIDO DE LA AGENDA ---"
			             cat archivo.txt
		
			            ;;
			
			        c)
			            echo "Ingrese desde qué línea hasta qué línea desea ver."
			
			            read -p "Línea inicial: " linea1
			            read -p "Línea final: " linea2
			
			            sed -n "${linea1},${linea2}p" archivo.txt
			            ;;
			
			        d)
			            read -p "Ingrese CI del usuario: " ci
			
			            echo "Ingrese el campo que desea ver:"
			            echo "nombre"
			            echo "apellido"
			            echo "telefono"
			            echo "fecha"
			
			            read -p "Campo: " campo
			
			            case $campo in
			
			                nombre)
			                    grep "^$ci;" archivo.txt | cut -d ";" -f 2
			                    ;;
			
			                apellido)
			                    grep "^$ci;" archivo.txt | cut -d ";" -f 3
			                    ;;
			
			                telefono)
			                    grep "^$ci;" archivo.txt | cut -d ";" -f 4
			                    ;;
			
			                fecha)
			                    grep "^$ci;" archivo.txt | cut -d ";" -f 5
			                    ;;
			
			                *)
			                    echo "Campo incorrecto."
			                    ;;
			            esac
			            ;;
			
			        e)
			            read -p "Ingrese la CI del usuario a eliminar: " usuario
			
			                grep -v "$usuario;" archivo.txt > temporal.txt
			                mv temporal.txt archivo.txt
			
			                echo "El usuario fue eliminado correctamente."
			            ;;
			
			        f)
			            read -p "Ingrese la CI del usuario: " ci
			            read -p "Ingrese el nuevo número de teléfono: " nuevoNumero

							en cponstruccion
            	;;

			5)
				dias= $(date +%j)
				dia= $(date +%A)
				mes= $(date +%B)
				año= $(date +%Y)
				date +%Y date +%B day+%A
				echo"Hoy es $dia de $mes de $año "
				echo"Han pasado $dias desde comienxo del año"
				;;

			6)			
				read -p "Ingrese el dia que desea mostrar (en numero)" dia
				read -p "Ingrese el mes que desea motrar (en numero)" mes
				read -p "Ingrese el año que desea mostrar (en numero)" año

				if ["$mes" -ge 1] && ["$mes" -le 12]; then
					if[cal "$mes" "$año"| grep -qw "$dia"]; then
					
					
				
					
				;;
        	0)
            		echo "Saliendo del sistema..."
            	;;

        	*)
        	    echo "Opcion invalida, intente de nuevo."
        	    ;;
    	esac

	done			

done 

